name = "orion-relay"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lobby"]
